import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import NavigationBar from '../components/NavigationBar';
import UseNavigationOpen from '../containers/UseNavigationOpen';
import Banner from '../components/Banner';
import AboutUs from '../components/AboutUs';
import Rooms from '../components/Rooms';
import Customer from '../components/Customer';

export default function Home() {
  const [openNavBar, handleOpenNavBar] = UseNavigationOpen();
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Grand Hotel</title>
        <link rel="shortcut icon" type="image/png" href="../img/crown.png" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
          crossorigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,300,300i,400,400i,600,600i,700,700i"
          rel="stylesheet"
        />
      </Head>
      <Sidebar openNavbar={openNavBar} handleNavBar={handleOpenNavBar} />
      <NavigationBar open={openNavBar} />
      <div className="container">
        <Banner />
        <AboutUs />
        <Rooms />
        <Customer />
      </div>
    </div>
  );
}
